# Generated by Django 3.2.3 on 2021-05-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_photo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='avatar',
            field=models.ImageField(upload_to='avatars', verbose_name='Картинка продукта'),
        ),
    ]
