# Generated by Django 3.2.3 on 2021-05-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_albumuser_photouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photouser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photouser',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlbumUser',
        ),
        migrations.DeleteModel(
            name='PhotoUser',
        ),
    ]
