# Generated by Django 3.2.3 on 2021-05-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_albumuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumUser',
        ),
    ]
